DROP TABLE IF EXISTS nessie.Trades;
DROP TABLE IF EXISTS nessie.TradeAttributes;
DROP TABLE IF EXISTS nessie.Counterparties;
CREATE TABLE nessie.Trades(CobDate DATE, TradeID VARCHAR, Notional DOUBLE);
CREATE TABLE nessie.TradeAttributes(CobDate DATE, TradeID VARCHAR, CounterpartyID VARCHAR, TradeDate DATE);
CREATE TABLE nessie.Counterparties(CounterpartyID VARCHAR, CounterpartyName VARCHAR);
INSERT INTO nessie.Trades VALUES (DATETYPE(2025,1,1), '1', 1000.00);
INSERT INTO nessie.Trades VALUES (DATETYPE(2025,1,1), '2', 2000.00);
INSERT INTO nessie.Trades VALUES (DATETYPE(2025,1,2), '1', 1100.00);
INSERT INTO nessie.Trades VALUES (DATETYPE(2025,1,2), '2', 2100.00);
INSERT INTO nessie.TradeAttributes VALUES (DATETYPE(2025,1,1),'1','Cpty1',DATETYPE(2024,11,1));
INSERT INTO nessie.TradeAttributes VALUES (DATETYPE(2025,1,1),'2','Cpty2',DATETYPE(2024,12,1));
INSERT INTO nessie.TradeAttributes VALUES (DATETYPE(2025,1,2),'1','Cpty1',DATETYPE(2024,11,1));
INSERT INTO nessie.TradeAttributes VALUES (DATETYPE(2025,1,2),'2','Cpty2',DATETYPE(2024,12,1));
INSERT INTO nessie.Counterparties VALUES ('Cpty1', 'Counterparty 1');
INSERT INTO nessie.Counterparties VALUES ('Cpty2', 'Counterparty 2');