otel:
  logs:
    exporter: otlp
  metrics:
    exporter: otlp
  metric:
    export:
      interval: 1s
  traces:
    exporter: otlp
    sampler: always_on
  resource:
    attributes:
      '[service.name]': ${spring.application.name}
      '[service.version]': 1.0
