otel:
  logs:
    exporter: none
  metrics:
    exporter: none
  traces:
    exporter: none
database:
  type: clickhouse
  in-memory-stores:
    partition-as-of-date: true
  clickhouse:
    host: localhost
    port: 8123
    database: AggUp
server:
  port: 9092
