otel:
  logs:
    exporter: none
  metrics:
    exporter: none
  traces:
    exporter: none
database:
  type: mssql
  in-memory-stores:
    partition-as-of-date: true
    vector-size: 3
  mssql:
    username: admin
    password: password
    port: 1234
    database: my-database
    schema: my-schema
server:
  port: 9092
