otel:
  logs:
    exporter: none
  metrics:
    exporter: none
  traces:
    exporter: none
server:
  port: 9091
database:
  type: datastore
  in-memory-stores:
    partition-as-of-date: true
dlc:
  jdbc:
    sources:
      Clickhouse:
        url: "jdbc:ch://localhost:8123?jdbc_ignore_unsupported_values=true&socket_timeout=30"
        username: test
        password: test
        driver-class: com.clickhouse.jdbc.ClickHouseDriver
  csv:
    local:
      sources:
        Test:
          root-base-dir: ./src/main/resources/data/#{AS_OF_DATE}

as-of-date:
  in-memory-dates:
    - 2024-09-02