otel:
  logs:
    exporter: none
  metrics:
    exporter: none
  traces:
    exporter: none
server:
  port: 9091
database:
  type: datastore
  in-memory-stores:
    partition-as-of-date: true
    vector-size: 3
dlc:
  csv:
    local:
      sources:
        Test:
          root-base-dir: ./src/main/resources/data/#{AS_OF_DATE}

as-of-date:
  in-memory-dates:
    - 2024-09-02