spring:
  security:
    saml2:
      relyingparty:
        registration:
          okta:
            assertingparty:
              metadata-uri: https://dev-75809299.okta.com/app/exkp6xkah8hfi1hQi5d7/sso/saml/metadata
              verification.credentials:
                - certificate-location: classpath:/saml/okta/okta-dev.crt

security:
  authentication:
    mode: saml
atoti:
  server:
    endpoint:
      activepivot:
        security:
          filters:
            authentication-flow:
              enabled: false
