otel:
  logs:
    exporter: none
  metrics:
    exporter: none
  traces:
    exporter: none
distribution:
  type: query
  cluster-id: atoti-cluster
  protocol-path: jgroups-protocols/protocol-tcp-gossip.xml