apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "atoti-chart.fullname" . }}-logs-pvc
  labels:
    {{- include "atoti-chart.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.logs.storage }}
