{{- if .Values.license }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "atoti-application.fullname" . }}-license
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "atoti-application.labels" . | nindent 4 }}
type: Opaque
stringData:
  ATOTI_LICENSE: {{ .Values.license | quote }}
{{- end }}
